export const JobStatus = {
    INITIALIZED: 'INITIALIZED',
    LABEL_DETECTION_STARTED: 'LABEL_DETECTION_STARTED',
    LABEL_DETECTION_IN_PROGRESS: 'LABEL_DETECTION_IN_PROGRESS',
    LABELS_DETECTED: 'LABELS_DETECTED',
    AUDIO_PROCESSING_STARTED: 'AUDIO_PROCESSING_STARTED',
    TRANSCRIPTION_IN_PROGRESS: 'TRANSCRIPTION_IN_PROGRESS',
    TRANSCRIPTION_COMPLETED: 'TRANSCRIPTION_COMPLETED',
    NARRATIVE_GENERATED: 'NARRATIVE_GENERATED',
    RESULTS_COMBINED: 'RESULTS_COMBINED',
    COMPLETED: 'COMPLETED',
    SAVED: 'SAVED',
    FAILED: 'FAILED'
} as const;

export type JobStatusType = typeof JobStatus[keyof typeof JobStatus];

export const ENV = {
    JOBS_TABLE: process.env.JOBS_TABLE || '',
    MEDIA_OUTPUT_BUCKET: process.env.MEDIA_OUTPUT_BUCKET || '',
    MEDIACONVERT_ENDPOINT: process.env.MEDIACONVERT_ENDPOINT || '',
    MEDIACONVERT_QUEUE: process.env.MEDIACONVERT_QUEUE || '',
    MEDIACONVERT_ROLE: process.env.MEDIACONVERT_ROLE || '',
    STATE_MACHINE_ARN: process.env.STATE_MACHINE_ARN || ''
} as const;
