title: movie4u Documentation
description: Video accessibility enhancement using AWS services
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
baseurl: "/movie4u"
show_downloads: false 